<!-- booking-date.php -->
<?php include "includes/header.php" ?>
<?php include "includes/navbar.php" ?>

<section class="relative overflow-hidden min-h-screen bg-white">
    <div class="py-16 px-4 md:px-[10%] font-main">

        <!-- Back Button -->
        <button onclick="window.location.href='services.php'"
            class="flex items-center text-[#3c5170] hover:text-[#fbb06b] transition-colors mb-8">
            <svg class="w-5 h-5 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7"></path>
            </svg>
            <span class="text-sm font-light">Back to Services</span>
        </button>

        <div class="max-w-3xl mx-auto">
            <!-- Service Info -->
            <div class="mb-12">
                <h2 class="text-4xl font-light text-[#3c5170] mb-2" id="serviceName">Loading...</h2>

            </div>

            <!-- Date Selection Header -->
            <div class="text-center mb-12">
                <h3 class="text-2xl font-light text-[#3c5170] mb-2">Select a Date</h3>
                <p class="text-sm text-gray-500">Your timezone: Asia/Singapore</p>
            </div>

            <!-- Calendar -->
            <div class="bg-white border border-gray-100 p-8 mb-8">
                <!-- Month Navigation -->
                <div class="flex justify-between items-center mb-8">
                    <button onclick="previousMonth()" class="p-2 hover:text-[#fbb06b] transition-colors">
                        <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7">
                            </path>
                        </svg>
                    </button>
                    <h4 class="text-xl font-light text-[#3c5170]" id="monthYear">November 2025</h4>
                    <button onclick="nextMonth()" class="p-2 hover:text-[#fbb06b] transition-colors">
                        <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7">
                            </path>
                        </svg>
                    </button>
                </div>

                <!-- Day Headers -->
                <div class="grid grid-cols-7 gap-2 mb-4">
                    <div class="text-center text-sm font-light text-gray-600 py-2">Mo</div>
                    <div class="text-center text-sm font-light text-gray-600 py-2">Tu</div>
                    <div class="text-center text-sm font-light text-gray-600 py-2">We</div>
                    <div class="text-center text-sm font-light text-gray-600 py-2">Th</div>
                    <div class="text-center text-sm font-light text-gray-600 py-2">Fr</div>
                    <div class="text-center text-sm font-light text-gray-600 py-2">Sa</div>
                    <div class="text-center text-sm font-light text-gray-600 py-2">Su</div>
                </div>

                <!-- Calendar Grid -->
                <div class="grid grid-cols-7 gap-2" id="calendarGrid">
                    <!-- Generated by JavaScript -->
                </div>
            </div>
        </div>
    </div>
</section>

<script>
    // booking-date.php JavaScript - Replace the existing script section
    let currentMonth = new Date().getMonth();
    let currentYear = new Date().getFullYear();

    // Load service from session storage
    document.addEventListener('DOMContentLoaded', function () {
        console.log('Booking date page loaded');

        const serviceRaw = sessionStorage.getItem('selectedService');
        console.log('Raw service data:', serviceRaw);

        if (!serviceRaw) {
            console.error('No service data found in sessionStorage');
            alert('Please select a service first');
            window.location.href = 'services.php';
            return;
        }

        try {
            let service = JSON.parse(serviceRaw);
            console.log('Parsed service:', service);

            // Handle if service is an array
            if (Array.isArray(service)) {
                console.log('Service is array, taking first element');
                service = service[0];
            }

            // Get service name from possible fields
            const serviceName = service.service_name || service.name || 'Service';
            console.log('Service name:', serviceName);

            document.getElementById('serviceName').textContent = serviceName;

        } catch (error) {
            console.error('Error parsing service data:', error);
            alert('Error loading service data. Please try again.');
            window.location.href = 'services.php';
            return;
        }

        generateCalendar();
    });

    function generateCalendar() {
        const firstDay = new Date(currentYear, currentMonth, 1).getDay();
        const daysInMonth = new Date(currentYear, currentMonth + 1, 0).getDate();
        const today = new Date();

        const monthNames = ["January", "February", "March", "April", "May", "June",
            "July", "August", "September", "October", "November", "December"];

        document.getElementById('monthYear').textContent = monthNames[currentMonth] + ' ' + currentYear;

        const grid = document.getElementById('calendarGrid');
        grid.innerHTML = '';

        // Adjust for Monday start (0 = Monday in our grid)
        let startDay = firstDay === 0 ? 6 : firstDay - 1;

        // Empty cells before first day
        for (let i = 0; i < startDay; i++) {
            const emptyCell = document.createElement('div');
            emptyCell.className = 'aspect-square';
            grid.appendChild(emptyCell);
        }

        // Day cells
        for (let day = 1; day <= daysInMonth; day++) {
            const dayCell = document.createElement('button');
            dayCell.className = 'aspect-square flex items-center justify-center text-sm transition-all duration-200 hover:bg-[#fbb06b] hover:text-white rounded-lg';
            dayCell.textContent = day;

            const cellDate = new Date(currentYear, currentMonth, day);
            const isPast = cellDate < new Date(today.getFullYear(), today.getMonth(), today.getDate());

            if (isPast) {
                dayCell.className += ' text-gray-300 cursor-not-allowed';
                dayCell.disabled = true;
            } else {
                dayCell.onclick = () => selectDate(day);
            }

            grid.appendChild(dayCell);
        }
    }

    function selectDate(day) {
        console.log('Date selected:', day);

        // Store the full date information
        const monthNames = ["January", "February", "March", "April", "May", "June",
            "July", "August", "September", "October", "November", "December"];

        const fullDate = `${day} ${monthNames[currentMonth]} ${currentYear}`;

        sessionStorage.setItem('selectedDate', fullDate);
        sessionStorage.setItem('selectedDay', day);
        sessionStorage.setItem('selectedMonth', currentMonth);
        sessionStorage.setItem('selectedYear', currentYear);

        console.log('Stored date:', fullDate);

        window.location.href = 'booking-time.php';
    }

    function previousMonth() {
        currentMonth--;
        if (currentMonth < 0) {
            currentMonth = 11;
            currentYear--;
        }
        generateCalendar();
    }

    function nextMonth() {
        currentMonth++;
        if (currentMonth > 11) {
            currentMonth = 0;
            currentYear++;
        }
        generateCalendar();
    }
</script>

<?php include "includes/footer.php" ?>